config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/SPECFEM/specfem3d:
      branch: master
      repo: https://github.com/SPECFEM/specfem3d
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/SPECFEM/specfem3d git:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-ivory-otter.sh
        container: qc.acc_scummy-pumpkin-maltese
  QC.Doc:
    repos:
      github.com/SPECFEM/specfem3d find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.cheeky-zucchini-gharial.sh
        container: qc.doc_stealthy-razzmatazz-mandrill
      github.com/SPECFEM/specfem3d git:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-goldenrod-rattlesnake.sh
        container: qc.doc_chewy-grey-serval
      github.com/SPECFEM/specfem3d markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.cloudy-lilac-eagle.sh
        container: qc.doc_zippy-sepia-schnauzer
  QC.Lic:
    repos:
      github.com/SPECFEM/specfem3d licensee:
        commands:
        - /usr/bin/env sh .sqa/script.boozy-sapphire-saola.sh
        container: qc.lic_ready-salmon-wolverine
  QC.Met:
    repos:
      github.com/SPECFEM/specfem3d cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.muzzy-yellow-tarsier.sh
        container: qc.met_scummy-razzmatazz-earwig
  QC.Sec:
    repos:
      github.com/SPECFEM/specfem3d bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-cerise-beaver.sh
        container: qc.sec_dorky-zucchini-bobcat
  QC.Sty:
    repos:
      github.com/SPECFEM/specfem3d flake8:
        commands:
        - /usr/bin/env sh .sqa/script.flaky-coral-dolphin.sh
        container: qc.sty_scanty-lime-mist
      github.com/SPECFEM/specfem3d oclint:
        commands:
        - /usr/bin/env sh .sqa/script.sleepy-blue-fish.sh
        container: qc.sty_muzzy-malachite-seal
  QC.Uni:
    repos:
      github.com/SPECFEM/specfem3d pytest:
        commands:
        - /usr/bin/env sh .sqa/script.whiny-magnolia-falcon.sh
        container: qc.uni_chummy-orchid-salamander
  QC.Ver:
    repos:
      github.com/SPECFEM/specfem3d get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.ready-gold-oriole.sh
        container: qc.ver_sleepy-zucchini-mist
timeout: 5400
