config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/SPECFEM/specfem3d:
      branch: master
      repo: https://github.com/SPECFEM/specfem3d
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/SPECFEM/specfem3d git:
        commands:
        - /usr/bin/env sh .sqa/script.seedy-taupe-axolotl.sh
        container: qc.acc_wheezy-pear-turkey
  QC.Doc:
    repos:
      github.com/SPECFEM/specfem3d find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.stuffy-red-angelfish.sh
        container: qc.doc_tasty-periwinkle-bongo
      github.com/SPECFEM/specfem3d git:
        commands:
        - /usr/bin/env sh .sqa/script.crabby-xanthic-crab.sh
        container: qc.doc_nerdy-lemon-caiman
      github.com/SPECFEM/specfem3d markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.ugly-dandelion-tiger.sh
        container: qc.doc_trippy-viridian-chipmunk
  QC.Lic:
    repos:
      github.com/SPECFEM/specfem3d licensee:
        commands:
        - /usr/bin/env sh .sqa/script.shabby-lemon-owl.sh
        container: qc.lic_homely-cinnabar-ladybird
  QC.Met:
    repos:
      github.com/SPECFEM/specfem3d cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.homely-yellow-wombat.sh
        container: qc.met_stealthy-cyan-zebra
  QC.Sec:
    repos:
      github.com/SPECFEM/specfem3d bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snazzy-sapphire-vulture.sh
        container: qc.sec_skimpy-ultramarine-neanderthal
  QC.Sty:
    repos:
      github.com/SPECFEM/specfem3d flake8:
        commands:
        - /usr/bin/env sh .sqa/script.cranky-orange-rabbit.sh
        container: qc.sty_woozy-brass-dodo
      github.com/SPECFEM/specfem3d oclint:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-yellow-rabbit.sh
        container: qc.sty_scummy-flax-mammoth
  QC.Uni:
    repos:
      github.com/SPECFEM/specfem3d pytest:
        commands:
        - /usr/bin/env sh .sqa/script.queasy-chestnut-dachsbracke.sh
        container: qc.uni_chummy-magenta-moorhen
  QC.Ver:
    repos:
      github.com/SPECFEM/specfem3d get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.snappy-pear-ostrich.sh
        container: qc.ver_randy-azure-sloth
timeout: 5400
